<?php

namespace Container37V08QN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D2eUg2iService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.D2eUg2i' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.D2eUg2i'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lieuRepository' => ['privates', 'App\\Repository\\LieuRepository', 'getLieuRepositoryService', true],
        ], [
            'lieuRepository' => 'App\\Repository\\LieuRepository',
        ]);
    }
}
