<?php

namespace ContainerORiGZRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C7pWWDtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C7pWWDt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C7pWWDt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\LieuController::delete' => ['privates', '.service_locator.mhAFZuk', 'get_ServiceLocator_MhAFZukService', true],
            'App\\Controller\\LieuController::edit' => ['privates', '.service_locator.mhAFZuk', 'get_ServiceLocator_MhAFZukService', true],
            'App\\Controller\\LieuController::index' => ['privates', '.service_locator.D2eUg2i', 'get_ServiceLocator_D2eUg2iService', true],
            'App\\Controller\\LieuController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\LieuController::show' => ['privates', '.service_locator.ZQGcgDR', 'get_ServiceLocator_ZQGcgDRService', true],
            'App\\Controller\\MaterielController::delete' => ['privates', '.service_locator.NgvlNzc', 'get_ServiceLocator_NgvlNzcService', true],
            'App\\Controller\\MaterielController::edit' => ['privates', '.service_locator.NgvlNzc', 'get_ServiceLocator_NgvlNzcService', true],
            'App\\Controller\\MaterielController::index' => ['privates', '.service_locator.YWOCxA9', 'get_ServiceLocator_YWOCxA9Service', true],
            'App\\Controller\\MaterielController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MaterielController::show' => ['privates', '.service_locator.9rl2zkG', 'get_ServiceLocator_9rl2zkGService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\LieuController:delete' => ['privates', '.service_locator.mhAFZuk', 'get_ServiceLocator_MhAFZukService', true],
            'App\\Controller\\LieuController:edit' => ['privates', '.service_locator.mhAFZuk', 'get_ServiceLocator_MhAFZukService', true],
            'App\\Controller\\LieuController:index' => ['privates', '.service_locator.D2eUg2i', 'get_ServiceLocator_D2eUg2iService', true],
            'App\\Controller\\LieuController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\LieuController:show' => ['privates', '.service_locator.ZQGcgDR', 'get_ServiceLocator_ZQGcgDRService', true],
            'App\\Controller\\MaterielController:delete' => ['privates', '.service_locator.NgvlNzc', 'get_ServiceLocator_NgvlNzcService', true],
            'App\\Controller\\MaterielController:edit' => ['privates', '.service_locator.NgvlNzc', 'get_ServiceLocator_NgvlNzcService', true],
            'App\\Controller\\MaterielController:index' => ['privates', '.service_locator.YWOCxA9', 'get_ServiceLocator_YWOCxA9Service', true],
            'App\\Controller\\MaterielController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MaterielController:show' => ['privates', '.service_locator.9rl2zkG', 'get_ServiceLocator_9rl2zkGService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\LieuController::delete' => '?',
            'App\\Controller\\LieuController::edit' => '?',
            'App\\Controller\\LieuController::index' => '?',
            'App\\Controller\\LieuController::new' => '?',
            'App\\Controller\\LieuController::show' => '?',
            'App\\Controller\\MaterielController::delete' => '?',
            'App\\Controller\\MaterielController::edit' => '?',
            'App\\Controller\\MaterielController::index' => '?',
            'App\\Controller\\MaterielController::new' => '?',
            'App\\Controller\\MaterielController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\LieuController:delete' => '?',
            'App\\Controller\\LieuController:edit' => '?',
            'App\\Controller\\LieuController:index' => '?',
            'App\\Controller\\LieuController:new' => '?',
            'App\\Controller\\LieuController:show' => '?',
            'App\\Controller\\MaterielController:delete' => '?',
            'App\\Controller\\MaterielController:edit' => '?',
            'App\\Controller\\MaterielController:index' => '?',
            'App\\Controller\\MaterielController:new' => '?',
            'App\\Controller\\MaterielController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
