<?php

namespace ContainerORiGZRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MhAFZukService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mhAFZuk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mhAFZuk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'lieu' => ['privates', '.errored..service_locator.mhAFZuk.App\\Entity\\Lieu', NULL, 'Cannot autowire service ".service_locator.mhAFZuk": it needs an instance of "App\\Entity\\Lieu" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'lieu' => 'App\\Entity\\Lieu',
        ]);
    }
}
