<?php

namespace ContainerO8m9SKO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaterielTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\MaterielType' shared autowired service.
     *
     * @return \App\Form\MaterielType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/MaterielType.php';

        return $container->privates['App\\Form\\MaterielType'] = new \App\Form\MaterielType();
    }
}
