<?php

namespace ContainerJump0VR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YO6wC9jService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yO6wC9j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yO6wC9j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorie' => ['privates', '.errored..service_locator.yO6wC9j.App\\Entity\\Categorie', NULL, 'Cannot autowire service ".service_locator.yO6wC9j": it needs an instance of "App\\Entity\\Categorie" but this type has been excluded in "config/services.yaml".'],
            'materiel' => ['privates', '.errored..service_locator.yO6wC9j.App\\Entity\\Materiel', NULL, 'Cannot autowire service ".service_locator.yO6wC9j": it needs an instance of "App\\Entity\\Materiel" but this type has been excluded in "config/services.yaml".'],
        ], [
            'categorie' => 'App\\Entity\\Categorie',
            'materiel' => 'App\\Entity\\Materiel',
        ]);
    }
}
