<?php

namespace ContainerJump0VR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VxbW2HKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VxbW2HK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VxbW2HK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CategorieController::MaterielShow' => ['privates', '.service_locator.yO6wC9j', 'get_ServiceLocator_YO6wC9jService', true],
            'App\\Controller\\CategorieController::delete' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\CategorieController::edit' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\CategorieController::index' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\CategorieController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategorieController::show' => ['privates', '.service_locator.j7wOkYK', 'get_ServiceLocator_J7wOkYKService', true],
            'App\\Controller\\LieuController::delete' => ['privates', '.service_locator.mhAFZuk', 'get_ServiceLocator_MhAFZukService', true],
            'App\\Controller\\LieuController::edit' => ['privates', '.service_locator.mhAFZuk', 'get_ServiceLocator_MhAFZukService', true],
            'App\\Controller\\LieuController::index' => ['privates', '.service_locator.D2eUg2i', 'get_ServiceLocator_D2eUg2iService', true],
            'App\\Controller\\LieuController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\LieuController::show' => ['privates', '.service_locator.ZQGcgDR', 'get_ServiceLocator_ZQGcgDRService', true],
            'App\\Controller\\MaterielController::delete' => ['privates', '.service_locator.NgvlNzc', 'get_ServiceLocator_NgvlNzcService', true],
            'App\\Controller\\MaterielController::edit' => ['privates', '.service_locator.NgvlNzc', 'get_ServiceLocator_NgvlNzcService', true],
            'App\\Controller\\MaterielController::index' => ['privates', '.service_locator.YWOCxA9', 'get_ServiceLocator_YWOCxA9Service', true],
            'App\\Controller\\MaterielController::new' => ['privates', '.service_locator.mhAFZuk', 'get_ServiceLocator_MhAFZukService', true],
            'App\\Controller\\MaterielController::show' => ['privates', '.service_locator.9rl2zkG', 'get_ServiceLocator_9rl2zkGService', true],
            'App\\Controller\\MemberController::index' => ['privates', '.service_locator.0luPVJ5', 'get_ServiceLocator_0luPVJ5Service', true],
            'App\\Controller\\MemberController::show' => ['privates', '.service_locator.0luPVJ5', 'get_ServiceLocator_0luPVJ5Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CategorieController:MaterielShow' => ['privates', '.service_locator.yO6wC9j', 'get_ServiceLocator_YO6wC9jService', true],
            'App\\Controller\\CategorieController:delete' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\CategorieController:edit' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\CategorieController:index' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\CategorieController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategorieController:show' => ['privates', '.service_locator.j7wOkYK', 'get_ServiceLocator_J7wOkYKService', true],
            'App\\Controller\\LieuController:delete' => ['privates', '.service_locator.mhAFZuk', 'get_ServiceLocator_MhAFZukService', true],
            'App\\Controller\\LieuController:edit' => ['privates', '.service_locator.mhAFZuk', 'get_ServiceLocator_MhAFZukService', true],
            'App\\Controller\\LieuController:index' => ['privates', '.service_locator.D2eUg2i', 'get_ServiceLocator_D2eUg2iService', true],
            'App\\Controller\\LieuController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\LieuController:show' => ['privates', '.service_locator.ZQGcgDR', 'get_ServiceLocator_ZQGcgDRService', true],
            'App\\Controller\\MaterielController:delete' => ['privates', '.service_locator.NgvlNzc', 'get_ServiceLocator_NgvlNzcService', true],
            'App\\Controller\\MaterielController:edit' => ['privates', '.service_locator.NgvlNzc', 'get_ServiceLocator_NgvlNzcService', true],
            'App\\Controller\\MaterielController:index' => ['privates', '.service_locator.YWOCxA9', 'get_ServiceLocator_YWOCxA9Service', true],
            'App\\Controller\\MaterielController:new' => ['privates', '.service_locator.mhAFZuk', 'get_ServiceLocator_MhAFZukService', true],
            'App\\Controller\\MaterielController:show' => ['privates', '.service_locator.9rl2zkG', 'get_ServiceLocator_9rl2zkGService', true],
            'App\\Controller\\MemberController:index' => ['privates', '.service_locator.0luPVJ5', 'get_ServiceLocator_0luPVJ5Service', true],
            'App\\Controller\\MemberController:show' => ['privates', '.service_locator.0luPVJ5', 'get_ServiceLocator_0luPVJ5Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CategorieController::MaterielShow' => '?',
            'App\\Controller\\CategorieController::delete' => '?',
            'App\\Controller\\CategorieController::edit' => '?',
            'App\\Controller\\CategorieController::index' => '?',
            'App\\Controller\\CategorieController::new' => '?',
            'App\\Controller\\CategorieController::show' => '?',
            'App\\Controller\\LieuController::delete' => '?',
            'App\\Controller\\LieuController::edit' => '?',
            'App\\Controller\\LieuController::index' => '?',
            'App\\Controller\\LieuController::new' => '?',
            'App\\Controller\\LieuController::show' => '?',
            'App\\Controller\\MaterielController::delete' => '?',
            'App\\Controller\\MaterielController::edit' => '?',
            'App\\Controller\\MaterielController::index' => '?',
            'App\\Controller\\MaterielController::new' => '?',
            'App\\Controller\\MaterielController::show' => '?',
            'App\\Controller\\MemberController::index' => '?',
            'App\\Controller\\MemberController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CategorieController:MaterielShow' => '?',
            'App\\Controller\\CategorieController:delete' => '?',
            'App\\Controller\\CategorieController:edit' => '?',
            'App\\Controller\\CategorieController:index' => '?',
            'App\\Controller\\CategorieController:new' => '?',
            'App\\Controller\\CategorieController:show' => '?',
            'App\\Controller\\LieuController:delete' => '?',
            'App\\Controller\\LieuController:edit' => '?',
            'App\\Controller\\LieuController:index' => '?',
            'App\\Controller\\LieuController:new' => '?',
            'App\\Controller\\LieuController:show' => '?',
            'App\\Controller\\MaterielController:delete' => '?',
            'App\\Controller\\MaterielController:edit' => '?',
            'App\\Controller\\MaterielController:index' => '?',
            'App\\Controller\\MaterielController:new' => '?',
            'App\\Controller\\MaterielController:show' => '?',
            'App\\Controller\\MemberController:index' => '?',
            'App\\Controller\\MemberController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
