<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGHafbHN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGHafbHN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGHafbHN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGHafbHN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGHafbHN\App_KernelDevDebugContainer([
    'container.build_hash' => 'GHafbHN',
    'container.build_id' => '1370bcdd',
    'container.build_time' => 1763332615,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGHafbHN');
