<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container37V08QN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container37V08QN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container37V08QN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container37V08QN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container37V08QN\App_KernelDevDebugContainer([
    'container.build_hash' => '37V08QN',
    'container.build_id' => 'd726a339',
    'container.build_time' => 1760125007,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container37V08QN');
