<?php

namespace ContainerD8tUF4q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLieuTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\LieuType' shared autowired service.
     *
     * @return \App\Form\LieuType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/LieuType.php';

        return $container->privates['App\\Form\\LieuType'] = new \App\Form\LieuType();
    }
}
